-- Generated by MineRider Control. The temporary file containing this script is
-- created with owner-only permissions and removed when the runtime exits.
local CONFIG = __PANEL_CONFIG__

local contexts = {}
local modes_by_username = {}
-- Protocol 769 item ids from the matching minecraft-data 1.21.4 registry.
-- They are used only as a fallback when a server hides the visible label in
-- an item component the wrapper cannot render to plain text.
local COMPASS_ITEM_ID = 961
local ELYTRA_ITEM_ID = 802
for _, account in ipairs(CONFIG.accounts) do
    modes_by_username[account.username] = account.mode
end

local function json_escape(value)
    return string.gsub(string.gsub(string.gsub(string.gsub(string.gsub(tostring(value), "\\", "\\\\"), '"', '\\"'), "\n", "\\n"), "\r", "\\r"), "\t", "\\t")
end

local function is_array(value)
    local count = 0
    local maximum = 0
    for key, _ in pairs(value) do
        if type(key) ~= "number" or key < 1 or key ~= math.floor(key) then return false end
        count = count + 1
        if key > maximum then maximum = key end
    end
    return count == maximum
end

local function json_encode(value, depth)
    depth = depth or 0
    if depth > 12 then return '"[depth-limit]"' end
    local kind = type(value)
    if kind == "nil" then return "null" end
    if kind == "boolean" then return value and "true" or "false" end
    if kind == "number" then return tostring(value) end
    if kind == "string" then return '"' .. json_escape(value) .. '"' end
    if kind ~= "table" then return '"[' .. json_escape(kind) .. ']"' end
    local output = {}
    if is_array(value) then
        for index = 1, #value do output[#output + 1] = json_encode(value[index], depth + 1) end
        return "[" .. table.concat(output, ",") .. "]"
    end
    for key, item in pairs(value) do
        output[#output + 1] = '"' .. json_escape(key) .. '":' .. json_encode(item, depth + 1)
    end
    return "{" .. table.concat(output, ",") .. "}"
end

local function emit(bot, status, message, extra)
    local event = extra or {}
    event.username = bot:username()
    event.worker_id = bot:worker_id()
    event.status = status
    event.message = message or status
    event.level = event.level or ((status == "error" or status == "kicked") and "error" or "info")
    minerider.info("@panel:" .. json_encode(event))
end

-- No bot object exists yet during swarm:configure (add_server/add_bot can
-- fail before any bot is created), so this is a distinct, bot-less "scope"
-- the panel routes to its swarm-wide error slot instead of a per-account
-- status. Called immediately before the `error()` that aborts configure().
local function emit_fatal(message, code)
    minerider.error("@panel:" .. json_encode({scope = "swarm", status = "fatal_error", code = code, message = message, level = "error"}))
end

local function normalize(value)
    local text = string.lower(tostring(value or ""))
    text = string.gsub(text, "ą", "a")
    text = string.gsub(text, "ć", "c")
    text = string.gsub(text, "ę", "e")
    text = string.gsub(text, "ł", "l")
    text = string.gsub(text, "ń", "n")
    text = string.gsub(text, "ó", "o")
    text = string.gsub(text, "ś", "s")
    text = string.gsub(text, "ź", "z")
    text = string.gsub(text, "ż", "z")
    return text
end

local function includes(text, fragment)
    return string.find(normalize(text), normalize(fragment), 1, true) ~= nil
end

local function includes_any(text, fragments)
    for _, fragment in ipairs(fragments) do
        if includes(text, fragment) then return true end
    end
    return false
end

local function item_text(item)
    if not item or item.empty then return "" end
    local parts = {item.custom_name or "", item.registry_name or ""}
    if item.lore then
        for _, line in ipairs(item.lore) do parts[#parts + 1] = line end
    end
    if item.components then
        for _, component in ipairs(item.components) do parts[#parts + 1] = component.data or "" end
    end
    return normalize(table.concat(parts, " "))
end

local function context(bot)
    local id = bot:id()
    local value = contexts[id]
    if not value then
        value = {phase = "starting", selector_attempts = 0, mode = modes_by_username[bot:username()] or "afk"}
        contexts[id] = value
    end
    return value
end

local function command(bot, value, label)
    local request_id = bot:command(value)
    if request_id then emit(bot, label or "command_sent", "Wysłano bezpieczną komendę serwera") end
    return request_id
end

local function click_boxpvp(bot)
    local view = bot:open_gui()
    if not view or not view.slots then return false end
    local fallback = nil
    for _, slot in ipairs(view.slots) do
        local text = item_text(slot)
        if includes(text, "boxpvp") then
            bot:click_gui(slot.raw_slot, "left", function(result)
                if result.ok then
                    context(bot).phase = "online"
                    emit(bot, "online", "Wybrano BOXPVP — bot pozostaje online")
                else
                    emit(bot, "error", "Kliknięcie BOXPVP nie powiodło się: " .. tostring(result.error and result.error.code or result.outcome), {level = "error"})
                end
            end)
            return true
        end
        if slot.raw_slot == 1 and not slot.empty then fallback = slot end
    end
    if fallback and (includes(item_text(fallback), "box") or fallback.item_id == ELYTRA_ITEM_ID) then
        bot:click_gui(fallback.raw_slot, "left")
        context(bot).phase = "online"
        emit(bot, "online", "Wybrano BOXPVP przez zweryfikowany slot zapasowy")
        return true
    end
    emit(bot, "error", "GUI wyboru trybu nie zawiera pozycji BOXPVP", {level = "error"})
    return false
end

local function try_open_mode_selector(bot)
    local ctx = context(bot)
    if ctx.phase == "verification_required" or ctx.phase == "online" or ctx.mode ~= "afk" then return end
    ctx.selector_attempts = ctx.selector_attempts + 1
    if ctx.selector_attempts > 18 then
        ctx.phase = "error"
        emit(bot, "error", "Nie znaleziono selektora trybu w hotbarze", {level = "error"})
        return
    end

    local hud = bot:hud()
    local hotbar = hud and hud.hotbar or nil
    if hotbar then
        for index, item in ipairs(hotbar) do
            local text = item_text(item)
            if includes_any(text, {"wybierz tryb", "ppm", "tryb gry"}) or item.item_id == COMPASS_ITEM_ID then
                ctx.phase = "selecting_mode"
                emit(bot, "selecting_mode", "Otwieranie GUI wyboru trybu")
                bot:select_hotbar_slot(index - 1)
                bot:set_timeout(350, function() bot:use_item("main") end)
                return
            end
        end
    end

    ctx.phase = "preparing"
    if ctx.selector_attempts == 1 or ctx.selector_attempts % 4 == 0 then
        emit(bot, "preparing", "Oczekiwanie na kompas wyboru trybu")
    end
    bot:set_timeout(2500, function() try_open_mode_selector(bot) end)
end

local function begin_mode(bot)
    local ctx = context(bot)
    if ctx.phase == "verification_required" or ctx.phase == "registering" or ctx.phase == "rules" then return end
    if ctx.mode == "register" then
        ctx.phase = "waiting_registration"
        emit(bot, "connected", "Oczekiwanie na prompt rejestracji")
        return
    end
    try_open_mode_selector(bot)
end

local function parse_captcha(text)
    local direct = string.match(text, "[Pp]rzepisz%s+kod%s*[:%-]?%s*([A-Za-z0-9_%-]+)")
    if direct then return direct end
    local candidate = nil
    for token in string.gmatch(text, "([A-Za-z0-9_%-]+)") do
        if #token >= 3 and #token <= 16 then candidate = token end
    end
    return candidate
end

local function handle_message(bot, raw)
    local text = tostring(raw or "")
    local normalized = normalize(text)
    if normalized == "" then return end
    local ctx = context(bot)

    if includes_any(normalized, {"weryfik", "verification"}) and includes_any(normalized, {"rusz", "ruch", "move", "sprawdz"}) then
        ctx.phase = "verification_required"
        emit(bot, "verification_required", "Serwer wymaga weryfikacji operatora; automatyczne obchodzenie nie jest wykonywane", {level = "warn"})
        return
    end

    if includes_any(normalized, {"/register", "/reg ", "zarejestr"}) then
        if ctx.mode ~= "register" then
            ctx.phase = "needs_registration"
            emit(bot, "needs_registration", "Konto wymaga rejestracji — uruchom je w trybie register", {level = "warn"})
            return
        end
        local captcha = parse_captcha(text)
        if not captcha then
            emit(bot, "error", "Nie udało się odczytać kodu rejestracyjnego", {level = "error"})
            return
        end
        ctx.phase = "registering"
        command(bot, "register " .. CONFIG.password .. " " .. CONFIG.password .. " " .. captcha, "registering")
        return
    end

    if includes_any(normalized, {"/login", "zaloguj", "login haslo", "login password"}) then
        ctx.phase = "authenticating"
        command(bot, "login " .. CONFIG.password, "authenticating")
        return
    end

    if includes_any(normalized, {"zalogowano", "pomyslnie", "successfully logged", "wybierz tryb"}) then
        ctx.phase = "authenticated"
        emit(bot, "connected", "Logowanie zakończone")
        bot:set_timeout(1200, function() begin_mode(bot) end)
    end
end

swarm:configure(function()
    local ok, err = swarm:add_server({
        name = CONFIG.server.name,
        host = CONFIG.server.host,
        port = CONFIG.server.port,
        view_distance = CONFIG.server.viewDistance,
        shared_chunks = CONFIG.server.sharedChunks,
        accept_resource_packs = CONFIG.server.acceptResourcePacks,
    })
    if not ok then
        emit_fatal("Nie udało się dodać serwera " .. tostring(CONFIG.server.name) .. ": " .. tostring(err.message), err.code)
        error(err.message)
    end

    local reconnect = {
        enabled = CONFIG.reconnect.enabled,
        max_retries = CONFIG.reconnect.maxRetries,
        initial_delay_ms = CONFIG.reconnect.initialDelayMs,
        max_delay_ms = CONFIG.reconnect.maxDelayMs,
        multiplier = CONFIG.reconnect.multiplier,
        jitter = {type = "deterministic", fraction = 0.15},
        stable_session_reset_ms = CONFIG.reconnect.stableSessionResetMs,
        on_transient = "retry",
        on_server_rejected = "stop",
        on_auth_failure = "stop",
        on_protocol_incompatible = "stop",
    }

    for index, account in ipairs(CONFIG.accounts) do
        local bot_id, bot_err = swarm:add_bot({
            id = index,
            username = account.username,
            server = CONFIG.server.name,
            reconnect = reconnect,
        })
        if not bot_id then
            emit_fatal("Nie udało się dodać konta " .. tostring(account.username) .. ": " .. tostring(bot_err.message), bot_err.code)
            error(bot_err.message)
        end
    end
end)

swarm:on("connecting", function(bot)
    context(bot).phase = "connecting"
    emit(bot, "connecting", "Łączenie z serwerem")
end)

swarm:on("connected", function(bot)
    local ctx = context(bot)
    ctx.phase = "connected"
    ctx.selector_attempts = 0
    emit(bot, "connected", "Połączono z serwerem")
    bot:set_timeout(3500, function()
        if context(bot).phase == "connected" then begin_mode(bot) end
    end)
end)

swarm:on("spawned", function(bot)
    emit(bot, "connected", "Bot pojawił się w świecie")
end)

swarm:on("chat", function(bot, event) handle_message(bot, event.message) end)
swarm:on("system_chat", function(bot, event) handle_message(bot, event.message) end)
swarm:on("action_bar", function(bot, event) handle_message(bot, event.text) end)
swarm:on("presentation", function(bot, event) handle_message(bot, event.message or event.text) end)

swarm:on("gui_opened", function(bot)
    local ctx = context(bot)
    if ctx.phase == "registering" or ctx.phase == "rules" then
        ctx.phase = "rules"
        emit(bot, "registering", "Akceptowanie regulaminu")
        bot:click_gui(11, "left", function(result)
            if result.ok then
                emit(bot, "registered", "Rejestracja i akceptacja regulaminu zakończone")
                bot:set_timeout(1000, function() bot:disconnect() end)
            else
                emit(bot, "error", "Nie udało się zaakceptować regulaminu", {level = "error"})
            end
        end)
        return
    end
    if ctx.phase == "selecting_mode" then click_boxpvp(bot) end
end)

swarm:on("hud", function(bot, event)
    local ctx = context(bot)
    if event.kind == "hotbar_changed" and (ctx.phase == "preparing" or ctx.phase == "authenticated") then
        try_open_mode_selector(bot)
    end
end)

swarm:on("disconnected", function(bot, event)
    context(bot).phase = "disconnected"
    emit(bot, "disconnected", "Rozłączono: " .. tostring(event.reason or "brak powodu"), {level = "warn"})
end)

swarm:on("reconnect_scheduled", function(bot, event)
    emit(bot, "connecting", "Zaplanowano ponowne połączenie", {attempt = event.attempt, delay_ms = event.delay_ms})
end)

swarm:on("kicked", function(bot, event)
    context(bot).phase = "kicked"
    emit(bot, "kicked", "Serwer rozłączył bota: " .. tostring(event.reason or "brak powodu"), {level = "error"})
end)

swarm:on("stopped", function(bot)
    context(bot).phase = "stopped"
    emit(bot, "stopped", "Bot zatrzymany")
end)

swarm:on("action_result", function(bot, event)
    if not event.ok and event.error and event.error.code ~= "not_connected" then
        emit(bot, "error", "Akcja MineRider nie powiodła się: " .. tostring(event.error.code), {level = "error"})
    end
end)

swarm:connect_all()
swarm:run()
