#!/usr/bin/env python3
"""Generate compact 1.21.4 state-id collision tables from vendored minecraft-data."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "crates/minerider-codegen/vendor/minecraft-data/pc/1.21.4"
OUT = ROOT / "src/minecraft/collision_data.rs"

blocks = json.loads((DATA / "blocks.json").read_text(encoding="utf-8"))
collision = json.loads((DATA / "blockCollisionShapes.json").read_text(encoding="utf-8"))
shape_ids = sorted(map(int, collision["shapes"].keys()))
if shape_ids != list(range(max(shape_ids) + 1)):
    raise SystemExit("collision shape ids are not dense")

shapes = []
for shape_id in shape_ids:
    boxes = collision["shapes"][str(shape_id)]
    if boxes and isinstance(boxes[0], (int, float)):
        boxes = [boxes]
    shapes.append(boxes)

max_state = max(block["maxStateId"] for block in blocks)
state_shapes = [None] * (max_state + 1)
for block in blocks:
    mapping = collision["blocks"].get(block["name"])
    if mapping is None:
        raise SystemExit(f"missing collision mapping for {block['name']}")
    count = block["maxStateId"] - block["minStateId"] + 1
    ids = mapping if isinstance(mapping, list) else [mapping] * count
    if len(ids) != count:
        raise SystemExit(
            f"state/shape count mismatch for {block['name']}: {count} != {len(ids)}"
        )
    for offset, shape in enumerate(ids):
        state_shapes[block["minStateId"] + offset] = shape

if any(shape is None for shape in state_shapes):
    raise SystemExit("global block-state id space has gaps")

flat_boxes = []
shape_ranges = []
for boxes in shapes:
    start = len(flat_boxes)
    flat_boxes.extend(boxes)
    shape_ranges.append((start, len(boxes)))

lines = [
    "//! @generated by scripts/generate_collision_data.py; do not edit.",
    "",
    "use super::physics::Aabb;",
    "",
    f"#[cfg(test)] pub const STATE_COUNT: usize = {len(state_shapes)};",
    "",
    "pub static SHAPE_BOXES: &[Aabb] = &[",
]
def rust_float(value):
    rendered = f"{value:.10g}"
    return rendered if "." in rendered or "e" in rendered.lower() else rendered + ".0"

for box in flat_boxes:
    lines.append("    Aabb::new(" + ", ".join(rust_float(value) for value in box) + "),")
lines += ["];", "", "pub static SHAPE_RANGES: &[(u16, u8)] = &["]
for start, count in shape_ranges:
    lines.append(f"    ({start}, {count}),")
lines += ["];", "", "pub static STATE_SHAPES: &[u16] = &["]
for start in range(0, len(state_shapes), 24):
    chunk = state_shapes[start : start + 24]
    lines.append("    " + ", ".join(map(str, chunk)) + ",")
lines += ["];", ""]
OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"wrote {OUT.relative_to(ROOT)}: {len(state_shapes)} states, {len(shapes)} shapes")
