#!/usr/bin/env python3
"""Generate compact 1.21.4 state-id collision tables from vendored minecraft-data."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "crates/minerider-codegen/vendor/minecraft-data/pc/1.21.4"
OUT = ROOT / "src/minecraft/collision_data.rs"

blocks = json.loads((DATA / "blocks.json").read_text(encoding="utf-8"))
collision = json.loads((DATA / "blockCollisionShapes.json").read_text(encoding="utf-8"))
shape_ids = sorted(map(int, collision["shapes"].keys()))
if shape_ids != list(range(max(shape_ids) + 1)):
    raise SystemExit("collision shape ids are not dense")

shapes = []
for shape_id in shape_ids:
    boxes = collision["shapes"][str(shape_id)]
    if boxes and isinstance(boxes[0], (int, float)):
        boxes = [boxes]
    shapes.append(boxes)

# Vanilla `Block.getFriction()` overrides (default 0.6). These constants are
# hardcoded in the 1.21.4 client's block classes, not present in minecraft-data,
# so we key them by block name and resolve state-id ranges from blocks.json.
# Honey block and soul sand keep the default 0.6 friction (their slowdowns are
# separate velocity multipliers, applied elsewhere).
FRICTION_OVERRIDES = {
    "slime_block": 0.8,
    "ice": 0.98,
    "packed_ice": 0.98,
    "frosted_ice": 0.98,
    "blue_ice": 0.989,
}
name_to_range = {block["name"]: (block["minStateId"], block["maxStateId"]) for block in blocks}
friction_ranges = []
for name, friction in FRICTION_OVERRIDES.items():
    if name not in name_to_range:
        raise SystemExit(f"friction override for unknown block {name}")
    lo, hi = name_to_range[name]
    friction_ranges.append((lo, hi, friction))
friction_ranges.sort()

max_state = max(block["maxStateId"] for block in blocks)
state_shapes = [None] * (max_state + 1)
for block in blocks:
    mapping = collision["blocks"].get(block["name"])
    if mapping is None:
        raise SystemExit(f"missing collision mapping for {block['name']}")
    count = block["maxStateId"] - block["minStateId"] + 1
    ids = mapping if isinstance(mapping, list) else [mapping] * count
    if len(ids) != count:
        raise SystemExit(
            f"state/shape count mismatch for {block['name']}: {count} != {len(ids)}"
        )
    for offset, shape in enumerate(ids):
        state_shapes[block["minStateId"] + offset] = shape

if any(shape is None for shape in state_shapes):
    raise SystemExit("global block-state id space has gaps")

flat_boxes = []
shape_ranges = []
for boxes in shapes:
    start = len(flat_boxes)
    flat_boxes.extend(boxes)
    shape_ranges.append((start, len(boxes)))

lines = [
    "//! @generated by scripts/generate_collision_data.py; do not edit.",
    "",
    "use super::physics::Aabb;",
    "",
    "#[cfg(test)]",
    "#[rustfmt::skip]",
    f"pub const STATE_COUNT: usize = {len(state_shapes)};",
    "",
    "#[rustfmt::skip]",
    "pub static SHAPE_BOXES: &[Aabb] = &[",
]
def rust_float(value):
    rendered = f"{value:.10g}"
    return rendered if "." in rendered or "e" in rendered.lower() else rendered + ".0"

for box in flat_boxes:
    lines.append("    Aabb::new(" + ", ".join(rust_float(value) for value in box) + "),")
lines += ["];", "", "#[rustfmt::skip]", "pub static SHAPE_RANGES: &[(u16, u8)] = &["]
for start, count in shape_ranges:
    lines.append(f"    ({start}, {count}),")
lines += ["];", "", "#[rustfmt::skip]", "pub static STATE_SHAPES: &[u16] = &["]
for start in range(0, len(state_shapes), 24):
    chunk = state_shapes[start : start + 24]
    lines.append("    " + ", ".join(map(str, chunk)) + ",")
lines += ["];", ""]
lines.append("/// Inclusive global state-id ranges whose block overrides the")
lines.append("/// default 0.6 friction, sorted by start id. Everything else is 0.6.")
lines.append("#[rustfmt::skip]")
lines.append("pub static FRICTION_OVERRIDES: &[(u32, u32, f32)] = &[")
for lo, hi, friction in friction_ranges:
    lines.append(f"    ({lo}, {hi}, {rust_float(friction)}),")
lines += ["];", ""]
OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"wrote {OUT.relative_to(ROOT)}: {len(state_shapes)} states, {len(shapes)} shapes")
